# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-30 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidColumnsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_columns_liquidcolumnspluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('num_columns', models.IntegerField(default=2, help_text='How many columns for this section?', verbose_name='columns')),
            ],
            options={
                'verbose_name': 'Liquid columns',
                'verbose_name_plural': 'Liquid columns',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
