# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_columns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidcolumnspluginmodel',
            name='num_columns',
            field=models.IntegerField(choices=[(2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six')], default=2, help_text='How many columns for this section?', verbose_name='columns'),
        ),
    ]
